language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "6"
  - "5"
  - "4"
install:
  - npm run lerna bootstrap
script:
  - npm run test-ci
  # - bithound check git@github.com:lagerjs/lager.git
