language: node_js
sudo: false
cache:
  directories:
    - node_modules
install:
  - bash travis-install.sh
# Matrix begin
node_js:
  - "6"
  - "4"
env:
  - TEST_SUITE=lager
  - TEST_SUITE=cli
  - TEST_SUITE=iam
  - TEST_SUITE=node-lambda
  - TEST_SUITE=api-gateway
  - TEST_SUITE=integration
# Matrix end
script:
  - bash travis-run.sh
