# We use a container that uses AWS Lambda's version of Node.js
node:
  build: docker-compose/nodejs
  env_file: docker-compose.env
  volumes:
    - .:/home/lager/.node/lib/node_modules/lager
    - ./dev-app:/home/lager/app
